branches:
  only:
    - master
    - stable
    - develop

language: php

php:
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=8.*
  - LARAVEL_VERSION=7.*

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - phpunit
